### ISSUE TITLE
FlatLink should be medium weight

### ISSUE THREAD

**Issue by TheaSommersletta** [SGFinansAS/elm-components#142]
Both flatlinks (mini and regular) should be medium font-weight, not regular

**Comment by morteako** [comment]
Is medium font-weight 500?
It seems to me like they both have font-weight 500 now?
At least there is no difference to my eye with font-weight set to 500

**Comment by TheaSommersletta** [comment]
Medium font-weight is 500. If I try to edit to font-weight: 500 in inspect here (https://nordea-elm-components.netlify.app/#Default/FlatLink/Default) it changes to the medium font

![Screenshot 2022-04-20 at 12 36 58](https://user-images.githubusercontent.com/43948832/164213052-8b0d96cb-009e-4410-b156-763747a97aee.png)
![Screenshot 2022-04-20 at 12 36 48](https://user-images.githubusercontent.com/43948832/164213055-c9b64e3e-c1bf-4b88-a1bf-98bf4397e26d.png)

**Comment by Eivinddh** [comment]
#142 should have fixed this ☺️
