### ISSUE TITLE
New: Slider

### ISSUE THREAD

**Issue by TheaSommersletta** [SGFinansAS/elm-components#175]
Default sliders allow users to set and select a single value. When the value is set, the input field is automatically updated with the value.

![Image](https://user-images.githubusercontent.com/43948832/169699042-2f3bebb0-1f71-4a27-abfc-50e21f50f138.png)

**Comment by hungqt** [comment]
We have a form of a slider here we can probably copy parts of 😄 

https://github.com/SGFinansAS/leasing-application/blob/main/src/Style.elm#L12
https://github.com/SGFinansAS/leasing-application/blob/main/src/Calculator.elm#L640
