### ISSUE TITLE
New: Uploaded file

### ISSUE THREAD

**Issue by mariongussiaas** [SGFinansAS/elm-components#193]
This already exists in Partnerhub

**Comment by mariongussiaas** [comment]
Component for uploaded file, i addition to the "upload file".

![Image](https://user-images.githubusercontent.com/97593413/169757999-da923e6a-a672-42f0-bd10-4b86a3e6a5c5.png)

https://www.figma.com/file/XSQT0h4JCmpWsCq4UyXWN3/Nordea-Design-Web-toolkit-V1.4.1?node-id=5215%3A43875

**Comment by fredrikloberg** [comment]
I think this is already existing (try to upload a file here): https://nordea-elm-components.netlify.app/#Components/FileUpload/Large%20(Single%20file)
