### ISSUE TITLE
Figure out a long term solution for building the Elm component library site

### ISSUE THREAD

**Issue by Eivinddh** [SGFinansAS/elm-components#285]
Right now I'm the only owner of the Netlify team that's responsible for the component library's builds. I'm moving to Stavanger at the end of April and to add another member to the Netlify team we need to pay monthly. We should see if there's an alternative where everyone has access to it, perhaps not in Netlify.

**Comment by Claudio-Pollice** [comment]
>  and to add another member to the Netlify team we need to pay monthly. 

also if we remove you as a member ?

**Comment by perok** [comment]
One suggestion is to move the hosting to the same setup we use in AWS.

**Comment by Eivinddh** [comment]
It is now moved on over to GitHub pages
https://github.com/SGFinansAS/elm-components/pull/297
